// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/mensajero.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Correcto struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Correcto) Reset()         { *m = Correcto{} }
func (m *Correcto) String() string { return proto.CompactTextString(m) }
func (*Correcto) ProtoMessage()    {}
func (*Correcto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{0}
}

func (m *Correcto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Correcto.Unmarshal(m, b)
}
func (m *Correcto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Correcto.Marshal(b, m, deterministic)
}
func (m *Correcto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Correcto.Merge(m, src)
}
func (m *Correcto) XXX_Size() int {
	return xxx_messageInfo_Correcto.Size(m)
}
func (m *Correcto) XXX_DiscardUnknown() {
	xxx_messageInfo_Correcto.DiscardUnknown(m)
}

var xxx_messageInfo_Correcto proto.InternalMessageInfo

func (m *Correcto) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ObtenerConLimite struct {
	Largo                int32    `protobuf:"varint,1,opt,name=largo,proto3" json:"largo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObtenerConLimite) Reset()         { *m = ObtenerConLimite{} }
func (m *ObtenerConLimite) String() string { return proto.CompactTextString(m) }
func (*ObtenerConLimite) ProtoMessage()    {}
func (*ObtenerConLimite) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{1}
}

func (m *ObtenerConLimite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObtenerConLimite.Unmarshal(m, b)
}
func (m *ObtenerConLimite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObtenerConLimite.Marshal(b, m, deterministic)
}
func (m *ObtenerConLimite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObtenerConLimite.Merge(m, src)
}
func (m *ObtenerConLimite) XXX_Size() int {
	return xxx_messageInfo_ObtenerConLimite.Size(m)
}
func (m *ObtenerConLimite) XXX_DiscardUnknown() {
	xxx_messageInfo_ObtenerConLimite.DiscardUnknown(m)
}

var xxx_messageInfo_ObtenerConLimite proto.InternalMessageInfo

func (m *ObtenerConLimite) GetLargo() int32 {
	if m != nil {
		return m.Largo
	}
	return 0
}

type ListaUsuarios struct {
	Usuarios             []string `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListaUsuarios) Reset()         { *m = ListaUsuarios{} }
func (m *ListaUsuarios) String() string { return proto.CompactTextString(m) }
func (*ListaUsuarios) ProtoMessage()    {}
func (*ListaUsuarios) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{2}
}

func (m *ListaUsuarios) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListaUsuarios.Unmarshal(m, b)
}
func (m *ListaUsuarios) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListaUsuarios.Marshal(b, m, deterministic)
}
func (m *ListaUsuarios) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListaUsuarios.Merge(m, src)
}
func (m *ListaUsuarios) XXX_Size() int {
	return xxx_messageInfo_ListaUsuarios.Size(m)
}
func (m *ListaUsuarios) XXX_DiscardUnknown() {
	xxx_messageInfo_ListaUsuarios.DiscardUnknown(m)
}

var xxx_messageInfo_ListaUsuarios proto.InternalMessageInfo

func (m *ListaUsuarios) GetUsuarios() []string {
	if m != nil {
		return m.Usuarios
	}
	return nil
}

type Registracion struct {
	UsuarioOrigen        string   `protobuf:"bytes,1,opt,name=usuarioOrigen,proto3" json:"usuarioOrigen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Registracion) Reset()         { *m = Registracion{} }
func (m *Registracion) String() string { return proto.CompactTextString(m) }
func (*Registracion) ProtoMessage()    {}
func (*Registracion) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{3}
}

func (m *Registracion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registracion.Unmarshal(m, b)
}
func (m *Registracion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registracion.Marshal(b, m, deterministic)
}
func (m *Registracion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registracion.Merge(m, src)
}
func (m *Registracion) XXX_Size() int {
	return xxx_messageInfo_Registracion.Size(m)
}
func (m *Registracion) XXX_DiscardUnknown() {
	xxx_messageInfo_Registracion.DiscardUnknown(m)
}

var xxx_messageInfo_Registracion proto.InternalMessageInfo

func (m *Registracion) GetUsuarioOrigen() string {
	if m != nil {
		return m.UsuarioOrigen
	}
	return ""
}

type TokenAutenticacion struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenAutenticacion) Reset()         { *m = TokenAutenticacion{} }
func (m *TokenAutenticacion) String() string { return proto.CompactTextString(m) }
func (*TokenAutenticacion) ProtoMessage()    {}
func (*TokenAutenticacion) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{4}
}

func (m *TokenAutenticacion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAutenticacion.Unmarshal(m, b)
}
func (m *TokenAutenticacion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAutenticacion.Marshal(b, m, deterministic)
}
func (m *TokenAutenticacion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAutenticacion.Merge(m, src)
}
func (m *TokenAutenticacion) XXX_Size() int {
	return xxx_messageInfo_TokenAutenticacion.Size(m)
}
func (m *TokenAutenticacion) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAutenticacion.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAutenticacion proto.InternalMessageInfo

func (m *TokenAutenticacion) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Vacio struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vacio) Reset()         { *m = Vacio{} }
func (m *Vacio) String() string { return proto.CompactTextString(m) }
func (*Vacio) ProtoMessage()    {}
func (*Vacio) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{5}
}

func (m *Vacio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vacio.Unmarshal(m, b)
}
func (m *Vacio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vacio.Marshal(b, m, deterministic)
}
func (m *Vacio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vacio.Merge(m, src)
}
func (m *Vacio) XXX_Size() int {
	return xxx_messageInfo_Vacio.Size(m)
}
func (m *Vacio) XXX_DiscardUnknown() {
	xxx_messageInfo_Vacio.DiscardUnknown(m)
}

var xxx_messageInfo_Vacio proto.InternalMessageInfo

// TODO: Crear un mensaje denominado MensajeApp que contenga dos cadenas:
// `usuario` y `cuerpo`.
type MensajeApp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MensajeApp) Reset()         { *m = MensajeApp{} }
func (m *MensajeApp) String() string { return proto.CompactTextString(m) }
func (*MensajeApp) ProtoMessage()    {}
func (*MensajeApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{6}
}

func (m *MensajeApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MensajeApp.Unmarshal(m, b)
}
func (m *MensajeApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MensajeApp.Marshal(b, m, deterministic)
}
func (m *MensajeApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MensajeApp.Merge(m, src)
}
func (m *MensajeApp) XXX_Size() int {
	return xxx_messageInfo_MensajeApp.Size(m)
}
func (m *MensajeApp) XXX_DiscardUnknown() {
	xxx_messageInfo_MensajeApp.DiscardUnknown(m)
}

var xxx_messageInfo_MensajeApp proto.InternalMessageInfo

// TODO: Crear un mensaje denominado MensajesApp que contenga una lista repetida
// de MensajeApp
type MensajesApp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MensajesApp) Reset()         { *m = MensajesApp{} }
func (m *MensajesApp) String() string { return proto.CompactTextString(m) }
func (*MensajesApp) ProtoMessage()    {}
func (*MensajesApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b95eb7da686dd0eb, []int{7}
}

func (m *MensajesApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MensajesApp.Unmarshal(m, b)
}
func (m *MensajesApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MensajesApp.Marshal(b, m, deterministic)
}
func (m *MensajesApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MensajesApp.Merge(m, src)
}
func (m *MensajesApp) XXX_Size() int {
	return xxx_messageInfo_MensajesApp.Size(m)
}
func (m *MensajesApp) XXX_DiscardUnknown() {
	xxx_messageInfo_MensajesApp.DiscardUnknown(m)
}

var xxx_messageInfo_MensajesApp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Correcto)(nil), "mensajero.Correcto")
	proto.RegisterType((*ObtenerConLimite)(nil), "mensajero.ObtenerConLimite")
	proto.RegisterType((*ListaUsuarios)(nil), "mensajero.ListaUsuarios")
	proto.RegisterType((*Registracion)(nil), "mensajero.Registracion")
	proto.RegisterType((*TokenAutenticacion)(nil), "mensajero.TokenAutenticacion")
	proto.RegisterType((*Vacio)(nil), "mensajero.Vacio")
	proto.RegisterType((*MensajeApp)(nil), "mensajero.MensajeApp")
	proto.RegisterType((*MensajesApp)(nil), "mensajero.MensajesApp")
}

func init() { proto.RegisterFile("pkg/mensajero.proto", fileDescriptor_b95eb7da686dd0eb) }

var fileDescriptor_b95eb7da686dd0eb = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x5d, 0x6b, 0xc2, 0x30,
	0x14, 0x45, 0x47, 0xd5, 0x5e, 0xed, 0x26, 0xd1, 0x6d, 0x52, 0x18, 0x48, 0xd8, 0x83, 0x6c, 0xa0,
	0x30, 0xfd, 0x03, 0xea, 0xf6, 0xa6, 0x08, 0x65, 0xdb, 0xc3, 0xde, 0x62, 0x09, 0x25, 0xeb, 0xcc,
	0x0d, 0x49, 0xdc, 0x4f, 0xda, 0xef, 0x1c, 0xfd, 0xb0, 0x46, 0xf4, 0xad, 0xe7, 0x9c, 0x7b, 0x6e,
	0xcf, 0x3d, 0x2d, 0xf4, 0x54, 0x9a, 0x4c, 0x76, 0x5c, 0x1a, 0xf6, 0xcd, 0x35, 0x8e, 0x95, 0x46,
	0x8b, 0xc4, 0xaf, 0x08, 0x1a, 0x42, 0x6b, 0x89, 0x5a, 0xf3, 0xd8, 0x22, 0xb9, 0x86, 0x3a, 0xa6,
	0x83, 0xda, 0xb0, 0x36, 0x6a, 0x45, 0x75, 0x4c, 0xe9, 0x08, 0xba, 0x9b, 0xad, 0xe5, 0x92, 0xeb,
	0x25, 0xca, 0x95, 0xd8, 0x09, 0xcb, 0x49, 0x1f, 0xbc, 0x1f, 0xa6, 0x13, 0xcc, 0xc7, 0xbc, 0xa8,
	0x00, 0xf4, 0x19, 0x82, 0x95, 0x30, 0x96, 0x7d, 0x98, 0x3d, 0xd3, 0x02, 0x0d, 0x09, 0xa1, 0xb5,
	0x2f, 0x9f, 0x07, 0xb5, 0xe1, 0xd5, 0xc8, 0x8f, 0x2a, 0x4c, 0x67, 0xd0, 0x89, 0x78, 0x22, 0x8c,
	0xd5, 0x2c, 0x16, 0x28, 0xc9, 0x23, 0x04, 0xa5, 0xb6, 0xd1, 0x22, 0xe1, 0x32, 0x5f, 0xed, 0x47,
	0xa7, 0x24, 0x7d, 0x02, 0xf2, 0x8e, 0x29, 0x97, 0xf3, 0xbd, 0xe5, 0xd2, 0x8a, 0xb8, 0xf0, 0xf6,
	0xc1, 0xb3, 0x19, 0x5b, 0x7a, 0x0a, 0x40, 0x9b, 0xe0, 0x7d, 0x66, 0x3a, 0xed, 0x00, 0xac, 0x8b,
	0x53, 0xe7, 0x4a, 0xd1, 0x00, 0xda, 0x25, 0x32, 0x73, 0xa5, 0x5e, 0xfe, 0xea, 0xe0, 0xaf, 0x0f,
	0x45, 0x90, 0x45, 0x56, 0x84, 0xe4, 0xb1, 0x65, 0x9a, 0xdc, 0x8f, 0x8f, 0x8d, 0xb9, 0x51, 0xc3,
	0x07, 0x47, 0xb8, 0x90, 0x66, 0x06, 0x8d, 0x37, 0xf9, 0x2b, 0x98, 0x26, 0xb7, 0xce, 0xe0, 0x31,
	0x41, 0xd8, 0x73, 0xe8, 0xaa, 0xf6, 0x29, 0x34, 0xcb, 0x9a, 0x49, 0xd7, 0xd1, 0xf3, 0x0b, 0xc2,
	0xbb, 0xf3, 0x45, 0x59, 0xf8, 0xec, 0x55, 0x79, 0xe3, 0x97, 0x3c, 0x03, 0x87, 0x39, 0xfd, 0x2c,
	0x33, 0x68, 0xbf, 0x72, 0x13, 0x1f, 0xee, 0x3c, 0xb7, 0x5e, 0x0a, 0xb8, 0xb8, 0xf9, 0x0a, 0x2a,
	0x76, 0xa2, 0xd2, 0x64, 0xdb, 0xc8, 0x7f, 0xa3, 0xe9, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7,
	0x3d, 0x7c, 0xfd, 0x5d, 0x02, 0x00, 0x00,
}
